# Generated by Django 3.2.23 on 2024-01-09 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_file', models.CharField(max_length=200)),
                ('title_dif', models.CharField(max_length=4)),
                ('title_th', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
                ('title_is', models.CharField(max_length=200)),
                ('text_note', models.TextField()),
                ('text_ph', models.TextField()),
                ('text_ex', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
